import crypto from 'crypto';
import busboy from 'busboy';
import { createClient } from '@supabase/supabase-js';
import Anthropic from '@anthropic-ai/sdk';

// Disable Vercel's automatic body parsing so we can handle raw streams
export const config = {
  api: { bodyParser: false },
};

// ── Clients ──────────────────────────────────────────────────────────────────

const supabase = createClient(
  process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY, // service role bypasses RLS
);

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ── Mailgun signature verification ───────────────────────────────────────────

function verifyMailgunSignature({ timestamp, token, signature }, signingKey) {
  if (!timestamp || !token || !signature || !signingKey) return false;

  // Reject timestamps older than 5 minutes to prevent replay attacks
  const age = Math.abs(Date.now() / 1000 - parseInt(timestamp, 10));
  if (age > 300) return false;

  const expected = crypto
    .createHmac('sha256', signingKey)
    .update(timestamp + token)
    .digest('hex');

  return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature));
}

// ── Body parsers ─────────────────────────────────────────────────────────────

function parseUrlEncoded(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (chunk) => chunks.push(chunk));
    req.on('end', () => {
      try {
        resolve(Object.fromEntries(new URLSearchParams(Buffer.concat(chunks).toString())));
      } catch (err) {
        reject(err);
      }
    });
    req.on('error', reject);
  });
}

function parseMultipart(req) {
  return new Promise((resolve, reject) => {
    const bb = busboy({ headers: req.headers });
    const fields = {};
    const files = {};

    bb.on('field', (name, value) => { fields[name] = value; });

    bb.on('file', (name, stream, info) => {
      const { filename, mimeType } = info;
      const chunks = [];
      stream.on('data', (chunk) => chunks.push(chunk));
      stream.on('end', () => {
        files[name] = { filename, mimeType, buffer: Buffer.concat(chunks) };
      });
    });

    bb.on('close', () => resolve({ fields, files }));
    bb.on('error', reject);
    req.pipe(bb);
  });
}

// ── Project resolution ───────────────────────────────────────────────────────
// Priority:
//   1. Recipient local part matches a project_number (e.g. prj-2024-001@inbound.punchlister.app)
//   2. Recipient local part is a project UUID
//   3. Sender email is a project member — use their first active project

async function resolveProject(recipientAddress, senderEmail) {
  let localPart = (recipientAddress || '').split('@')[0].toLowerCase();

  // Strip an "inbox+" (or any "prefix+") plus-addressing label, e.g.
  //   inbox+2d88d345  →  2d88d345
  if (localPart.includes('+')) {
    localPart = localPart.split('+').slice(1).join('+');
  }

  if (localPart) {
    // Try full UUID match
    const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (uuidPattern.test(localPart)) {
      const { data } = await supabase.from('projects').select('id').eq('id', localPart).maybeSingle();
      if (data) return data.id;
    }

    // Try short prefix of UUID (first 8 hex chars, as generated by the frontend)
    if (/^[0-9a-f]{8}$/i.test(localPart)) {
      const { data: byPrefix } = await supabase
        .from('projects')
        .select('id')
        .ilike('id', `${localPart}%`)
        .limit(2);
      if (byPrefix?.length === 1) return byPrefix[0].id;
      if (byPrefix?.length > 1) {
        console.warn('[inbound-email] short prefix collision for', localPart, '— refusing to guess');
      }
    }

    // Try project_number match (case-insensitive)
    const { data: byNumber } = await supabase
      .from('projects')
      .select('id')
      .ilike('project_number', localPart)
      .maybeSingle();
    if (byNumber) return byNumber.id;
  }

  // Fallback: look up sender in project_members
  if (senderEmail) {
    const { data: membership } = await supabase
      .from('project_members')
      .select('project_id, projects(status)')
      .eq('email', senderEmail.toLowerCase())
      .order('created_at', { ascending: true })
      .limit(1)
      .maybeSingle();

    if (membership) return membership.project_id;

    // Fallback: owner of the project
    const { data: ownedProject } = await supabase
      .from('projects')
      .select('id, owner:auth_users(email)')
      .limit(1)
      .maybeSingle();

    // Check auth.users for owner match — simplified: just grab owner's first project
    const { data: projects } = await supabase
      .from('projects')
      .select('id, owner_id')
      .order('created_at', { ascending: true })
      .limit(10);

    if (projects?.length) {
      // Try to match owner email via auth.users
      for (const project of projects) {
        const { data: authUser } = await supabase.auth.admin.getUserById(project.owner_id);
        if (authUser?.user?.email?.toLowerCase() === senderEmail.toLowerCase()) {
          return project.id;
        }
      }
      // Last resort: first project in the system
      return projects[0].id;
    }
  }

  return null;
}

// ── AI classification (mirrors /api/process-log) ──────────────────────────────

async function classifyNote(note, location = '') {
  const response = await anthropic.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 900,
    messages: [{
      role: 'user',
      content: `You are an AI assistant for a Belgian construction project manager. Process this site-visit memo (or inbound email body) and extract structured data. Return ONLY valid JSON — no markdown, no code blocks, just raw JSON.

Note: "${note}"
Provided Location: "${location || ''}"

Return exactly this JSON structure:
{
  "summary": "1-2 sentence professional summary in Dutch",
  "type": "delay|safety|progress|material|rfi|dispute|general",
  "disputeTypes": [],
  "flags": ["short tag 1", "short tag 2"],
  "impact": "none|schedule|cost|safety",
  "actionRequired": true or false,
  "suggestRFI": true or false,
  "extractedLocation": null or "location string found in the note",
  "extractedDate": null or "YYYY-MM-DD date found in the note",
  "workpoints": [
    {
      "description": "concrete one-sentence description of one distinct work-point in Dutch",
      "type": "general|delay|safety|progress|material|rfi|dispute",
      "amount": null or numeric estimated cost in EUR if mentioned,
      "responsible": null or short string (subcontractor/role)
    }
  ]
}

Rules:
- A single memo usually contains 1–5 distinct work-points (separate decisions, agreements, defects, requests, complaints). Split them out into the workpoints[] array — DO NOT collapse multiple things into one description.
- workpoints[].description must be self-contained in Dutch (no pronouns referring to other points).
- workpoints[].amount: extract any euro amount tied to a specific point ("ongeveer 2840 euro" → 2840); else null.
- workpoints[].responsible: who is on the hook (subcontractor name, "bouwheer", "architect", "leverancier"); else null.
- type "delay": any work stoppage; safety: hazard; progress: milestone; material: supply; rfi: needs clarification; dispute: adversarial claim; general: otherwise.
- disputeTypes: only when type='dispute'. Subset of timing | meerwerk | kwaliteit | betaling | other.
- flags: 1-3 short phrases max.
- suggestRFI: true if any work-point needs formal designer/engineer clarification.`,
    }],
  });

  const raw = response.content[0].text.trim()
    .replace(/^```(?:json)?\n?/, '')
    .replace(/\n?```$/, '');
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed.disputeTypes)) parsed.disputeTypes = [];
  if (!Array.isArray(parsed.workpoints))   parsed.workpoints   = [];
  parsed.workpoints = parsed.workpoints.map(wp => ({
    description: String(wp.description || '').trim(),
    type:        wp.type || 'general',
    amount:      wp.amount != null ? Number(wp.amount) : null,
    responsible: wp.responsible || null,
  })).filter(wp => wp.description.length > 0);
  return parsed;
}

// ── Auto-create dispute ───────────────────────────────────────────────────────

async function createDisputeFromEmail({ projectId, fieldLogId, senderEmail, subject, disputeTypes, summary }) {
  // Count existing disputes for this project to generate a number
  const { count } = await supabase
    .from('disputes')
    .select('id', { count: 'exact', head: true })
    .eq('project_id', projectId);

  const number = `DIS-${String((count || 0) + 1).padStart(3, '0')}`;

  const { data: dispute, error } = await supabase
    .from('disputes')
    .insert({ project_id: projectId, field_log_id: fieldLogId, number, sender_email: senderEmail, subject, status: 'open' })
    .select()
    .single();

  if (error) {
    console.error('[inbound-email] Failed to create dispute:', error.message);
    return;
  }

  // Create a dispute point per detected dispute type
  const points = disputeTypes.map(type => ({
    dispute_id: dispute.id,
    type,
    description: summary,
  }));

  const { error: pointsErr } = await supabase.from('dispute_points').insert(points);
  if (pointsErr) console.error('[inbound-email] Failed to create dispute points:', pointsErr.message);

  console.log('[inbound-email] Created dispute', dispute.number, 'with', points.length, 'point(s)');
}

// ── Handler ──────────────────────────────────────────────────────────────────

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const contentType = (req.headers['content-type'] || '').toLowerCase();
  let fields = {};
  let files = {};

  try {
    if (contentType.includes('multipart/form-data')) {
      ({ fields, files } = await parseMultipart(req));
    } else if (contentType.includes('application/x-www-form-urlencoded')) {
      fields = await parseUrlEncoded(req);
    } else {
      return res.status(406).json({ error: 'Unsupported content-type' });
    }
  } catch (err) {
    console.error('[inbound-email] Body parsing failed:', err);
    return res.status(406).json({ error: 'Failed to parse request body' });
  }

  // Verify Mailgun webhook signature
  if (!verifyMailgunSignature(
    { timestamp: fields.timestamp, token: fields.token, signature: fields.signature },
    process.env.MAILGUN_WEBHOOK_SIGNING_KEY,
  )) {
    console.warn('[inbound-email] Signature verification failed');
    return res.status(406).json({ error: 'Invalid signature' });
  }

  // Extract email content
  const sender    = fields.sender || fields.from || '';
  const recipient = fields.recipient || '';
  const subject   = fields.subject || '';
  const noteText  = (fields['stripped-text'] || fields['body-plain'] || '').trim();

  // Extract sender email address
  const senderEmail = (sender.match(/<([^>]+)>/) || [])[1] || sender.trim();

  if (!noteText) {
    console.warn('[inbound-email] Empty email body — ignoring');
    return res.status(200).json({ success: true, message: 'Empty body, nothing to log' });
  }

  // Resolve which project this email belongs to
  const projectId = await resolveProject(recipient, senderEmail);
  if (!projectId) {
    console.error('[inbound-email] Could not resolve project for recipient:', recipient, 'sender:', senderEmail);
    return res.status(200).json({ success: false, message: 'No matching project found' });
  }

  // Combine subject + body as the raw note (subject gives useful context)
  const rawNote = subject ? `${subject}\n\n${noteText}` : noteText;

  // Reply threading: parse In-Reply-To header (Mailgun forwards as 'In-Reply-To' or 'message-headers').
  // If we sent the parent message, link this inbound to it and stamp last_reply_at.
  const inReplyToRaw = fields['In-Reply-To'] || fields['in-reply-to'] || '';
  const inReplyToId = inReplyToRaw.replace(/^<|>$/g, '').trim() || null;
  let parentOutboundId = null;
  if (inReplyToId) {
    const { data: parent } = await supabase
      .from('outbound_emails')
      .select('id, project_id, field_log_id')
      .eq('message_id', inReplyToId)
      .maybeSingle();
    if (parent) {
      parentOutboundId = parent.id;
      // If we don't have a project resolution yet but the parent does, prefer it
      // (already resolved above; this is just a safety net for projectId mismatches).
      await supabase
        .from('outbound_emails')
        .update({ status: 'replied', last_reply_at: new Date().toISOString() })
        .eq('id', parent.id);
    }
  }

  console.log('[inbound-email] Creating field log:', { projectId, senderEmail, subject, rawNote: rawNote.slice(0, 120), parentOutboundId });

  // Insert field log with processing: true
  const { data: entry, error: insertError } = await supabase
    .from('field_logs')
    .insert({
      project_id: projectId,
      raw_note: rawNote,
      type: 'general',
      processing: true,
      source: 'email',
      user_email: senderEmail || null,
      in_reply_to_message_id: inReplyToId,
      parent_outbound_email_id: parentOutboundId,
    })
    .select()
    .single();

  if (insertError) {
    console.error('[inbound-email] Failed to insert field log:', insertError.message);
    return res.status(500).json({ error: 'Failed to create field log' });
  }

  // Respond immediately so Mailgun doesn't retry (must reply within a few seconds)
  res.status(200).json({ success: true, logId: entry.id });

  // Classify the note asynchronously (after response is sent)
  try {
    const data = await classifyNote(rawNote);

    const updates = {
      processed_summary: data.summary,
      type: data.type,
      flags: data.flags,
      impact: data.impact,
      action_required: data.actionRequired,
      suggest_rfi: data.suggestRFI,
      workpoints: data.workpoints || [],
      processing: false,
      ...(data.type === 'dispute' && data.disputeTypes?.length ? { dispute_types: data.disputeTypes } : {}),
      ...(data.extractedLocation ? { location: data.extractedLocation } : {}),
      ...(data.extractedDate    ? { log_date: data.extractedDate }     : {}),
    };

    await supabase.from('field_logs').update(updates).eq('id', entry.id);

    // Per-workpoint classification against signed offerte (if any)
    if ((data.workpoints || []).length > 0) {
      try {
        const { data: ctx } = await supabase
          .from('project_context').select('*').eq('project_id', projectId)
          .in('category', ['quote', 'contract']);
        if (ctx?.length) {
          const cls = await anthropic.messages.create({
            model: 'claude-haiku-4-5-20251001',
            max_tokens: 1200,
            messages: [{
              role: 'user',
              content: `Beoordeel of elk werkpunt binnen de getekende offerte valt of meerwerk is.\n\nOFFERTE:\n${ctx.map(i => `[${i.title}]\n${(i.content || '').slice(0, 1500)}`).join('\n---\n')}\n\nWERKPUNTEN:\n${data.workpoints.map((wp, i) => `${i + 1}. ${wp.description}`).join('\n')}\n\nReturn ONLY a JSON array of length ${data.workpoints.length}, one entry per werkpunt:\n[{"index": 1, "classification": "in_scope|meerwerk|twijfel", "reasoning": "max 2 zinnen NL", "confidence": "high|medium|low"}]`,
            }],
          });
          const arr = JSON.parse(cls.content[0].text.trim().replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, ''));
          const merged = data.workpoints.map((wp, i) => ({
            ...wp,
            classification: arr[i]?.classification || 'twijfel',
            reasoning:      arr[i]?.reasoning      || '',
            confidence:     arr[i]?.confidence     || 'low',
          }));
          await supabase.from('field_logs').update({ workpoints: merged }).eq('id', entry.id);
        }
      } catch (clsErr) {
        console.warn('[inbound-email] classify-meerwerk failed:', clsErr.message);
      }
    }

    console.log('[inbound-email] Classified log', entry.id, '→ type:', data.type, 'impact:', data.impact);

    // Auto-create dispute record when email is classified as a dispute
    if (data.type === 'dispute' && data.disputeTypes?.length) {
      await createDisputeFromEmail({
        projectId,
        fieldLogId: entry.id,
        senderEmail,
        subject,
        disputeTypes: data.disputeTypes,
        summary: data.summary,
      });
    }
  } catch (err) {
    console.error('[inbound-email] Classification failed for log', entry.id, ':', err.message);
    await supabase.from('field_logs').update({ processing: false }).eq('id', entry.id);
  }
}
